name: "POSIX"
on: [push]

jobs:
  tests:
    name: "ghc-tags-plugin"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v10
      - name: "cachix"
        uses: cachix/cachix-action@v6
        with:
          name: "ghc-tags-plugin"
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'

      - name: "cachix iohk"
        run: cachix use iohk

      - name: "[GHC 8.6.5]  ghc-tags-core"
        run: nix-build default.nix --argstr compiler ghc865 -A ghc-tags-core
      - name: "[GHC 8.6.5]  ghc-tags-plugin"
        run: nix-build default.nix --argstr compiler ghc865 -A ghc-tags-plugin

      - name: "[GHC 8.8.4]  ghc-tags-core"
        run: nix-build default.nix --argstr compiler ghc884 -A ghc-tags-core
      - name: "[GHC 8.8.4]  ghc-tags-plugin"
        run: nix-build default.nix --argstr compiler ghc884 -A ghc-tags-plugin

      - name: "[GHC 8.10.2] ghc-tags-core"
        run: nix-build default.nix --argstr compiler ghc8102 -A ghc-tags-core
      - name: "[GHC 8.10.2] ghc-tags-plugin"
        run: nix-build default.nix --argstr compiler ghc8102 -A ghc-tags-plugin
